version: "3"
services:
  user:
    restart: always
    image: mysql:5.7
    container_name: user
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - ./volumes/mysql/user:/var/lib/mysql
  company:
    restart: always
    image: mysql:5.7
    container_name: company
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=company
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - ./volumes/mysql/company:/var/lib/mysql
