spring:
  profiles: stage
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://172.21.114.112:3306/spring_batch?serverTimezone=UTC
      username: hbot
      password: hbot12#
      driver-class-name: com.mysql.jdbc.Driver
  h2:
    console:
      enabled: true

spring.batch.job.names: ${job.name:NONE}