spring:
  profiles: default
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

spring.batch.job.names: ${job.name:NONE}