spring:
  profiles: stage
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: admin
      password: password
      driver-class-name: com.mysql.jdbc.Driver
  h2:
    console:
      enabled: true

spring.batch.job.names: ${job.name:NONE}