version: "3"
services:
  batch:
    restart: always
    image: mysql:5.7
    container_name: oauth2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=oauth2
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - ./volumes/mysql:/var/lib/mysql