feign:
  client:
    config:
      default:
        loggerLevel: FULL

external-api:
  http-bin: http://127.0.0.1:8080

logging.level.com.guide.openfeign.infra: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa