spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      pool-name: Hikari
      maximum-pool-size: 20
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true

  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.SQL: debug    # SQL이 logger로 출력됨
  org.hibernate.type: trace   # SQL 바인딩 파라미터를 보려고 할 경우

