cloud:
  aws:
    credentials:
      access-key: AKIA2RZAXHKXS3D24IVM
      secret-key: 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
    region:
      static: ap-northeast-2 # AWS SQS의 리전정보
    stack:
      auto: false
    sqs:
      queue:
        name: MyQueue.fifo
        url: https://sqs.ap-northeast-2.amazonaws.com/725381233327/MyQueue.fifo # 생성한 SQS 큐 url
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level --- [%thread] %logger{35} : %msg %n'